[SERVICE]
    Flush 1
    Daemon Off
    Log_level info

[INPUT]
    Name tail
    Path /app/logs/app.log
    Tag app.logs
    Refresh_Interval 5

[OUTPUT]
    Name kafka
    Match *
    Brokers kafka:9092
    Format json
    Topics logs-topic