[SERVICE]
    Flush 1
    Daemon Off
    Log_level info
    # Parsers_File parsers.conf

[INPUT]
    Name tail
    Path /logs/app.sample.log
    Tag app.logs

[OUTPUT]
    Name kafka
    Match *
    Format json